# Generated by Django 2.2.19 on 2022-04-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220408_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
